# Site settings
email: contato@richardsonlima.com.br 
baseurl: "http://blog.richardsonlima.com.br"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Blog Richardson Lima 
description: Blog Richardson Lima
url: ""
twitter_username: infradevops
default_img: 

# Profile settings
name: Richardson Lima 
profile_img: https://raw.githubusercontent.com/richardsonlima/blog/master/images/avatar-big-richardsonlima.jpg
profile: 
social:
  github: richardsonlima
  linkedin: richardsonlima
  twitter: infradevops


# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
