# Site settings
email: contato@richardsonlima.com.br 
baseurl: "http://blog.richardsonlima.com.br"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: RichOps Things
description: Blog RichOps Things
url: ""
twitter_username: infradevops
default_img: https://raw.githubusercontent.com/richardsonlima/blog/master/images/avatar-big-richardsonlima.jpg

# Profile settings
name: Richardson Lima 
profile_img: https://raw.githubusercontent.com/richardsonlima/blog/master/images/avatar-big-richardsonlima-2000x1200.jpg
profile: I'm an Information Technology Infrastructure Analyst , I have a strong focus on Cloud computing, DevOps things, Ethical Hacking, IoT, Python and Ruby Programming language.
social:
  github: https://github.com/richardsonlima
  linkedin: http://us.linkedin.com/in/richardsonlima
  twitter: http://twitter.com/infradevops


# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
